const RADIUS = 10;
const ANIMATION_SPEED = 20;
const ANIMATION_DURATION = 0.2;
const INITIAL_DASH_OFFSET = 0.03;
const STROKE_WIDTH = 5;

export { RADIUS, STROKE_WIDTH, INITIAL_DASH_OFFSET, ANIMATION_SPEED, ANIMATION_DURATION };
