const WIDTH = 800;
const HEIGHT = 400;
const MONTH_UNIT = 12;
const BORDER_COLOR = "#CCD3D3";
const VIEW_BOX_WIDTH = 200;
const VIEW_BOX_HEIGHT = 100;
const MONTH_FONT_SIZE = 5;
const MONTH_LABEL_DY = 5;
const MONTH_TEXT_COLOR = "#8D9393";
const VALUE_TEXT_COLOR = "#626666";
const DURATION = 2;
const BORDER_ANIMATION_SPEED = 0.05;
const VERTICAL_DIVIDE_LINE_SPEED = 0.1;
const HORIZONTAL_DIVIDE_LINE_SPEED = 0.1;
const LINE_ANIMATION_SPEED = 0.1;
const BORDER_STROKE_WIDTH = 0.3;
const VALUE_TEXT_SIZE = 4.5;
const VALUE_TEXT_WEIGHT = 700;
const LINE_LENGTH_COMPENSATION = 0.35;
const LINE_STROKE_WIDTH = 0.5;
const KEY_SPLINES = "0.1 0.8 0.2 1;0.1 0.8 0.2 1";
const KEY_TIMES = "0;0.5;1";
const DEFAULT_POINT_RADIUS = 1.5;
const SCALE_UP_POINT_RADIUS = 2;
const MIN_BOUNDARY = 10000;
const OFFSET_UP = "7";
const OFFSET_DOWN = "-2";
const LIMIT_DOWN_TO_UP = 8;

export {
  WIDTH,
  HEIGHT,
  MONTH_UNIT,
  BORDER_COLOR,
  VIEW_BOX_WIDTH,
  VIEW_BOX_HEIGHT,
  MONTH_FONT_SIZE,
  MONTH_LABEL_DY,
  MONTH_TEXT_COLOR,
  VALUE_TEXT_COLOR,
  DURATION,
  BORDER_ANIMATION_SPEED,
  LINE_ANIMATION_SPEED,
  VERTICAL_DIVIDE_LINE_SPEED,
  HORIZONTAL_DIVIDE_LINE_SPEED,
  BORDER_STROKE_WIDTH,
  VALUE_TEXT_SIZE,
  VALUE_TEXT_WEIGHT,
  LINE_LENGTH_COMPENSATION,
  LINE_STROKE_WIDTH,
  KEY_TIMES,
  KEY_SPLINES,
  DEFAULT_POINT_RADIUS,
  SCALE_UP_POINT_RADIUS,
  MIN_BOUNDARY,
  OFFSET_UP,
  OFFSET_DOWN,
  LIMIT_DOWN_TO_UP,
};
